#----------------------------------------------------------------#
# 構文補完
#----------------------------------------------------------------#
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
on_event = 'InsertCharPre'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
'''

#----------------------------------------------------------------------------------#
# コメントアウト補助
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'tyru/caw.vim'
on_i = 1
hook_add = '''
  " 行の最初の文字の前にコメント文字をトグル
  nmap <Leader>/ <Plug>(caw:hatpos:toggle)
  vmap <Leader>/ <Plug>(caw:hatpos:toggle)
  " 行頭にコメントをトグル
  nmap <Leader>0 <Plug>(caw:zeropos:toggle)
  vmap <Leader>0 <Plug>(caw:zeropos:toggle)
'''

#----------------------------------------------------------------#
# javascript補完
#----------------------------------------------------------------#
[[plugins]]
repo = 'neovim/node-host'
on_ft = ['javascript', 'javascript.jsx']
hook_post_update = '''
  let g:dein#plugin.build = 'yarn add'
'''

[[plugins]]
repo = 'billyvg/tigris.nvim'
on_ft = ['javascript', 'javascript.jsx']
hook_post_update = '''
  let g:dein#plugin.build = './install.sh'
'''
hook_add = '''
  let g:tigris#enabled = 1
  let g:tigris#on_the_fly_enabled = 1
  let g:tigris#delay = 200
'''

#----------------------------------------------------------------#
# Syntax Highlight
#----------------------------------------------------------------#
[[plugins]] # javascript全般
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'javascript.jsx']
hook_add = '''
  let g:polyglot_disabled = ['javascript', 'javascript.jsx']
'''

[[plugins]] # jsx
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = ['javascript', 'javascript.jsx']
depends = ['yajs.vim']
