[[plugins]]
repo = 'Shougo/deol.nvim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'soramugi/auto-ctags.vim'

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'reireias/vim-cheatsheet'

[[plugins]]
repo = 'scrooloose/nerdtree'
