[[plugins]]
repo = 'Shougo/deol.nvim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/deoplete-rct'

[[plugins]]
repo = 'osyo-manga/vim-monster'

[[plugins]]
repo = 'soramugi/auto-ctags.vim'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'slim-template/vim-slim'
