#----------------------------------------------------------------------------------#
# toml管理で便利
#----------------------------------------------------------------------------------#
[[plugins]]
# カーソル位置のコンテキストに合わせてftを切り替える
on_source = 'context_filetype.vim'
repo = 'osyo-manga/vim-precious'

[[plugins]]
# カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

#----------------------------------------------------------------------------------#
# colorscheme
#----------------------------------------------------------------------------------#
[[plugins]]
hook_add = '''
  colorscheme kanagawa
'''
repo = 'rebelot/kanagawa.nvim'

#----------------------------------------------------------------------------------#
# statusline拡張
#----------------------------------------------------------------------------------#
[[plugins]]
hook_add = 'source ~/.config/nvim/plugins/lightline.lua'
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'josa42/nvim-lightline-lsp'
depends = ['lightline.vim']

#----------------------------------------------------------------------------------#
# LSP
#----------------------------------------------------------------------------------#
[[plugins]]
hook_add = 'source ~/.config/nvim/plugins/nvim-lspconfig.lua'
repo = 'neovim/nvim-lspconfig'

#----------------------------------------------------------------------------------#
# インデント補助
#----------------------------------------------------------------------------------#
[[plugins]]
lua_add = '''
  require("ibl").setup()

'''
repo = 'lukas-reineke/indent-blankline.nvim'

#----------------------------------------------------------------------------------#
# ファイルブラウザ補助
#----------------------------------------------------------------------------------#
[[plugins]]
hook_add = 'source ~/.config/nvim/plugins/fern.lua'
repo = 'lambdalisue/fern.vim'

[[plugins]]
on_source = 'fern.vim'
repo = 'lambdalisue/fern-git-status.vim'

#----------------------------------------------------------------------------------#
# gitツール
#----------------------------------------------------------------------------------#
[[plugins]]
hook_add = 'source ~/.config/nvim/plugins/vim-fugitive.lua'
repo = 'tpope/vim-fugitive'

[[plugins]]
# github
depends = ['vim-fugitive']
repo = 'tpope/vim-rhubarb'

#----------------------------------------------------------------------------------#
# 移動補完
#----------------------------------------------------------------------------------#
[[plugins]]
# vimの移動コマンド拡張
lua_add = '''
  -- Disable default mappings
  vim.g.EasyMotion_do_mapping = 0
  vim.api.nvim_set_keymap('n', '<Leader>e', '<Plug>(easymotion-overwin-f2)', {noremap = true})
  vim.api.nvim_set_keymap('n', '[EasyM]', '<Nop>', {})
  vim.api.nvim_set_keymap('n', '<Leader><Space>', '[EasyM]', {})
  -- Gif config
  vim.api.nvim_set_keymap('', '[EasyM]s', '<Plug>(easymotion-lineforward)', {noremap = true})
  vim.api.nvim_set_keymap('', '[EasyM]t', '<Plug>(easymotion-j)', {noremap = true})
  vim.api.nvim_set_keymap('', '[EasyM]n', '<Plug>(easymotion-k)', {noremap = true})
  vim.api.nvim_set_keymap('', '[EasyM]k', '<Plug>(easymotion-linebackward)', {noremap = true})
  -- keep cursor column when JK motion
  vim.g.EasyMotion_startofline = 0 
  vim.g.EasyMotion_smartcase = 1
'''
repo = 'easymotion/vim-easymotion'

#----------------------------------------------------------------------------------#
# 置き換え強化
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'tpope/vim-abolish'
# crs "SnakeCase" → "snake_case"
# crm "mixed_case" → "MixedCase"
# crc "camel_case" → "camelCase"
# cru "upper_case" → "UPPER_CASE"

[[plugins]]
repo = 'tpope/vim-surround'
# [e] 囲いの文字
# [d] 目的の文字
# ds [e] delete surround
# cs [e] [d] change surround
# ys iw [d] you surround

#----------------------------------------------------------------------------------#
# カッコ補完
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'cohama/lexima.vim'

