#----------------------------------------------------------------------------------#
# 必須
#----------------------------------------------------------------------------------#
[[plugins]] # deinで必須
repo = 'Shougo/vimproc.vim'
build = 'make'

#----------------------------------------------------------------------------------#
# toml管理で便利
#----------------------------------------------------------------------------------#
[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

#----------------------------------------------------------------------------------#
# colorscheme
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
  colorscheme gruvbox
  set background=dark
  let g:gruvbox_contrast_dark = 'soft'
'''

#----------------------------------------------------------------------------------#
# statusline拡張 ale利用
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.config/nvim/royautoload/plugins/plugins-lightline.vim'
depends = ['vim-devicons']

#----------------------------------------------------------------------------------#
# 非同期検証ツール
#----------------------------------------------------------------------------------#

[[plugins]]
repo = 'neoclide/coc.nvim'
build = './install.sh nightly'
merge = 0
hook_add = 'source ~/.config/nvim/royautoload/plugins/plugins-coc.vim'

#----------------------------------------------------------------------------------#
# インデント補助
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
  let g:indent_guides_start_level = 2
  let g:indent_guides_guide_size = 1
'''

#----------------------------------------------------------------------------------#
# ファイルブラウザ補助
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = 'source ~/.config/nvim/royautoload/plugins/plugins-denite.vim'
hook_post_source = '''
  call denite#custom#var('file/rec', 'command',
    \ ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
  call denite#custom#var('grep', 'command', ['ag'])
  call denite#custom#var('grep', 'default_opts',
    \ ['--vimgrep', '--no-heading'])
  call denite#custom#var('grep', 'recursive_opts', [])
  call denite#custom#var('grep', 'pattern_opt', ['--regexp'])
  call denite#custom#var('grep', 'separator', ['--'])
  call denite#custom#var('grep', 'final_opts', [])

  " 高速マッチャcpsm使用
  call denite#custom#source('file/rec', 'matchers', ['matcher/cpsm', 'matcher_ignore_globs'])
  call denite#custom#filter('matcher_ignore_globs', 'ignore_globs',
       \ [ '*~', '*.o', '*.exe', '*.bak', '*.lock',
       \ '.DS_Store', '*.pyc', '*.sw[po]', '*.class',
       \ '.hg/', '.git/', '.bzr/', '.svn/',
       \ 'node_modules/.bin/', 'bower_components/', 'tmp/', 'log/', 'vendor/ruby',
       \ '.idea/', 'dist/',
       \ 'tags', 'tags-*',
       \ 'GTAGS', 'GRTAGS', 'GPATH'])
'''

[[plugins]]
repo = '5t111111/denite-rails'
depends = ['denite.nvim']

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = 'source ~/.config/nvim/royautoload/plugins/plugins-defx.vim'

[[plugins]]
repo = 'kristijanhusak/defx-icons'
depends = ['defx.nvim']

[[plugins]]
repo = 'kristijanhusak/defx-git'
depends = ['defx.nvim']
#----------------------------------------------------------------------------------#
# 高速検索ツール
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'nixprime/cpsm'
build = 'sh -c "env PY3=ON ./install.sh"'

#----------------------------------------------------------------------------------#
# gitツール
#----------------------------------------------------------------------------------#
[[plugins]]
repo = "tpope/vim-fugitive"
hook_add = 'source ~/.config/nvim/royautoload/plugins/plugins-vim-fugitive.vim'

[[plugins]] # bitbucket
repo = "tommcdo/vim-fubitive"
depends = ['vim-fugitive']

[[plugins]] # github
repo = "tpope/vim-rhubarb"
depends = ['vim-fugitive']

[[plugins]] # gitlab
repo = "shumphrey/fugitive-gitlab.vim"
depends = ['vim-fugitive']

#----------------------------------------------------------------------------------#
# カッコ補完
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'cohama/lexima.vim'

#----------------------------------------------------------------------------------#
# コメントアウト補助
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'tyru/caw.vim'
on_i = 1
hook_add = '''
  " 行の最初の文字の前にコメント文字をトグル
  nmap <Leader>/ <Plug>(caw:hatpos:toggle)
  vmap <Leader>/ <Plug>(caw:hatpos:toggle)
  " 行頭にコメントをトグル
  nmap <Leader>0 <Plug>(caw:zeropos:toggle)
  vmap <Leader>0 <Plug>(caw:zeropos:toggle)
'''

#----------------------------------------------------------------------------------#
# 移動補完
#----------------------------------------------------------------------------------#
[[plugins]] # vimの移動コマンド拡張
repo = 'easymotion/vim-easymotion'
hook_add = '''
  " Disable default mappings
  let g:EasyMotion_do_mapping = 0
  nmap s <Plug>(easymotion-overwin-f2)
  " Gif config
  map <Leader>l <Plug>(easymotion-lineforward)
  map <Leader>j <Plug>(easymotion-j)
  map <Leader>k <Plug>(easymotion-k)
  map <Leader>h <Plug>(easymotion-linebackward)
  " keep cursor column when JK motion
  let g:EasyMotion_startofline = 0 
  let g:EasyMotion_smartcase = 1
'''

#----------------------------------------------------------------------------------#
# 置き換え強化
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'tpope/vim-abolish'
# crs "SnakeCase" → "snake_case"
# crm "mixed_case" → "MixedCase"
# crc "camel_case" → "camelCase"
# cru "upper_case" → "UPPER_CASE"

#----------------------------------------------------------------------------------#
# icons
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'ryanoasis/vim-devicons'
dependes =['lightline']
hook_add = '''
  let g:webdevicons_enable = 1
  let g:webdevicons_enable_denite = 1
'''

#----------------------------------------------------------------------------------#
# terminal拡張 TODO
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'Shougo/deol.nvim'

