[[plugins]]
# カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'

[[plugins]]
# カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

#----------------------------------------------------------------------------------#
# colorscheme
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'rebelot/kanagawa.nvim'
lua_add = 'vim.cmd([[colorscheme kanagawa]])'

#----------------------------------------------------------------------------------#
# statusline拡張
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'itchyny/lightline.vim'
lua_add = 'vim.cmd([[source ~/.config/nvim/plugins/lightline.lua]])'

#----------------------------------------------------------------------------------#
# LSP
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'neovim/nvim-lspconfig'
depends = ['ddc-source-lsp']
lua_add = 'vim.cmd([[source ~/.config/nvim/plugins/nvim-lspconfig.lua]])'

[[plugins]]
repo = 'Shougo/ddc-source-lsp'

#----------------------------------------------------------------------------------#
# Github copilot
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'github/copilot.vim'
lua_source = 'vim.cmd([[source ~/.config/nvim/plugins/copilot.lua]])'

#----------------------------------------------------------------------------------#
# インデント補助
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'
lua_add = 'require("ibl").setup()'

#----------------------------------------------------------------------------------#
# ファイルブラウザ補助
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'lambdalisue/fern.vim'
lua_add = 'vim.cmd([[source ~/.config/nvim/plugins/fern.lua]])'

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'
depends = ['fern.vim']

[[plugins]]
repo = 'lambdalisue/fern-hijack.vim'
depends = ['fern.vim', 'fern-git-status.vim']

#----------------------------------------------------------------------------------#
# gitツール
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'tpope/vim-fugitive'
lua_add = 'vim.cmd([[source ~/.config/nvim/plugins/vim-fugitive.lua]])'

[[plugins]]
repo = 'airblade/vim-gitgutter'

#----------------------------------------------------------------------------------#
# 移動補完
#----------------------------------------------------------------------------------#
[[plugins]]
# vimの移動コマンド拡張
repo = 'easymotion/vim-easymotion'
lua_add = 'vim.cmd([[source ~/.config/nvim/plugins/vim-easymotion.lua]])'

#----------------------------------------------------------------------------------#
# 置き換え強化
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'tpope/vim-abolish'
# crs "SnakeCase" → "snake_case"
# crm "mixed_case" → "MixedCase"
# crc "camel_case" → "camelCase"
# cru "upper_case" → "UPPER_CASE"

[[plugins]]
repo = 'tpope/vim-surround'
# [e] 囲いの文字
# [d] 目的の文字
# ds [e] delete surround
# cs [e] [d] change surround
# ys iw [d] you surround

#----------------------------------------------------------------------------------#
# カッコ補完
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'cohama/lexima.vim'
