#----------------------------------------------------------------------------------#

#----------------------------------------------------------------------------------#
[[plugins]]
# deinで必須
repo = 'Shougo/vimproc.vim'
build = 'make'

#----------------------------------------------------------------------------------#
# toml管理で便利
#----------------------------------------------------------------------------------#
[[plugins]]
# カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
on_source = 'context_filetype.vim'

[[plugins]]
# カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

#----------------------------------------------------------------------------------#
# colorscheme
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'rebelot/kanagawa.nvim'
hook_add = '''
  colorscheme kanagawa
'''

#----------------------------------------------------------------------------------#
# statusline拡張
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.config/nvim/plugins/lightline.vim'

#----------------------------------------------------------------------------------#
# Denops
#----------------------------------------------------------------------------------#

[[plugins]]
repo = 'vim-denops/denops.vim'

# [[plugins]]
# repo = 'neovim/nvim-lspconfig'
# hook_add = 'source ~/.config/nvim/plugins/vim-lsp.vim'
# 
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = 'source ~/.config/nvim/plugins/vim-lsp.vim'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
merged = 0
hook_add = '''
  let g:lsp_settings = {
  \  'clangd': {
  \    'disabled': v:true
  \  },
  \  'css-languageserver': {
  \    'workspace_config': {
  \      'css': {
  \        'validate': v:false
  \      },
  \      'scss': {
  \        'validate': v:false
  \      },
  \      'less': {
  \        'validate': v:false
  \      }
  \    }
  \  }
  \}
  let g:lsp_settings_filetype_ruby = ['solargraph']
'''

[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
  let g:ale_disable_lsp = 1
  let g:ale_sign_column_always = 1
  let g:ale_fix_on_save = 1
  let g:ale_fixers = {
  \   'ruby': ['rubocop'],
  \   'typescript': ['eslint'],
  \   'javascript': ['eslint'],
  \   'svelte': ['eslint'],
  \   'css': ['stylelint'],
  \   'scss': ['stylelint'],
  \   'sass': ['stylelint'],
  \   'less': ['stylelint'],
  \}
  let g:ale_linter_aliases = {
  \   'svelte': ['svelte', 'typescript'],
  \}
'''

#----------------------------------------------------------------------------------#
# インデント補助
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
  let g:indent_guides_start_level = 2
  let g:indent_guides_guide_size = 1
'''

#----------------------------------------------------------------------------------#
# ファイルブラウザ補助
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = 'source ~/.config/nvim/plugins/fern.vim'

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'
on_source = 'fern.vim'

#----------------------------------------------------------------------------------#
# gitツール
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = 'source ~/.config/nvim/plugins/vim-fugitive.vim'

[[plugins]]
# github
repo = 'tpope/vim-rhubarb'
depends = ['vim-fugitive']

#----------------------------------------------------------------------------------#
# コメントアウト補助
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
  " 行の最初の文字の前にコメント文字をトグル
  nmap <Leader>j <Plug>(caw:hatpos:toggle)
  vmap <Leader>j <Plug>(caw:hatpos:toggle)
  " 行頭にコメントをトグル
  nmap <Leader>J <Plug>(caw:zeropos:toggle)
  vmap <Leader>J <Plug>(caw:zeropos:toggle)
'''

#----------------------------------------------------------------------------------#
# 移動補完
#----------------------------------------------------------------------------------#
[[plugins]]
# vimの移動コマンド拡張
repo = 'easymotion/vim-easymotion'
hook_add = '''
  " Disable default mappings
  let g:EasyMotion_do_mapping = 0
  nmap <Leader><Space> <Plug>(easymotion-overwin-f2)
  nnoremap [EasyM] <Nop>
  nmap f [EasyM]

  " Gif config
  map [EasyM]s <Plug>(easymotion-lineforward)
  map [EasyM]t <Plug>(easymotion-j)
  map [EasyM]n <Plug>(easymotion-k)
  map [EasyM]k <Plug>(easymotion-linebackward)

  " keep cursor column when JK motion
  let g:EasyMotion_startofline = 0 
  let g:EasyMotion_smartcase = 1
'''

#----------------------------------------------------------------------------------#
# 置き換え強化
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'tpope/vim-abolish'
# crs "SnakeCase" → "snake_case"
# crm "mixed_case" → "MixedCase"
# crc "camel_case" → "camelCase"
# cru "upper_case" → "UPPER_CASE"

[[plugins]]
repo = 'tpope/vim-surround'
# [e] 囲いの文字
# [d] 目的の文字
# ds [e] delete surround
# cs [e] [d] change surround
# ys iw [d] you surround

#----------------------------------------------------------------------------------#
# カッコ補完
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'cohama/lexima.vim'

