#----------------------------------------------------------------------------------#
# 高速検索ツール
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'Shougo/ddu.vim'
lua_source = 'vim.cmd([[source ~/.config/nvim/plugins/ddu.lua]])'
on_event = 'BufRead'

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'

[[plugins]]
repo = 'shun/ddu-source-rg'
on_source = 'ddu.vim'

[[plugins]]
repo = 'shun/ddu-source-buffer'
on_source = 'ddu.vim'

[[plugins]]
repo = 'lambdalisue/mr.vim'
on_source = 'ddu-source-mr'

[[plugins]]
repo = 'kuuote/ddu-source-mr'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-register'
on_source = 'ddu.vim'

#----------------------------------------------------------------------------------#
# 非同期検証ツール
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'Shougo/ddc.vim'
lua_source = 'vim.cmd([[source ~/.config/nvim/plugins/ddc.lua]])'
on_event = 'InsertEnter'

[[plugins]]
repo = 'Shougo/ddc-ui-pum'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'

[[plugins]]
repo = 'matsui54/ddc-matcher_fuzzy'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'

[[plugins]]
repo = 'matsui54/ddc-buffer'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-copilot'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/pum.vim'
on_source = 'ddc-ui-pum'


#----------------------------------------------------------------#
# Syntax Highlight
#----------------------------------------------------------------#
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_post_update = 'TSUpdate'
lua_source = 'vim.cmd([[source ~/.config/nvim/plugins/nvim-treesitter.lua]])'
merged = 0
on_event = 'BufRead'

[[plugins]]
# haskell
repo = 'neovimhaskell/haskell-vim'
on_ft = ['haskell']

#----------------------------------------------------------------#
# Config for each Lang
#----------------------------------------------------------------#

[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = ['go']

#----------------------------------------------------------------#
# for Haskell
#----------------------------------------------------------------#
[[plugins]]
# haskell indent
repo = 'nbouscal/vim-stylish-haskell'
on_ft = ['haskell']
