#----------------------------------------------------------------#
# Syntax Highlight
#----------------------------------------------------------------#
[[plugins]] # markdown
repo = 'godlygeek/tabular'
on_ft = ['markdown']
depends = ['vim-markdown']

[[plugins]] # markdown
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']
hook_source = '''
  autocmd BufNewFile,BufReadPost *.md set filetype=markdown
  let g:vim_markdown_folding_disabled = 1
'''

[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = ['go']

#----------------------------------------------------------------#
# Config for each Lang
#----------------------------------------------------------------#

[[plugins]]
repo = 'prettier/vim-prettier'
build = 'yarn install'
on_ft = ['typescript', 'typescriptreact', 'javascript', 'javascriptreact', 'css', 'less', 'scss', 'json', 'graphql', 'markdown', 'vue', 'yaml', 'html']
hook_source = '''
  let g:prettier#autoformat = 0
  autocmd BufWritePre *.js,*.jsx,*.mjs,*.ts,*.tsx,*.css,*.less,*.scss,*.json,*.graphql,*.md,*.vue,*.yaml,*.html PrettierAsync
'''

#----------------------------------------------------------------#
# for Haskell
#----------------------------------------------------------------#
[[plugins]] # haskell indent
repo = 'nbouscal/vim-stylish-haskell'
on_ft = ['haskell']

[[plugins]] # haskell use :h hoogle
repo = 'Twinside/vim-hoogle'
on_ft = ['haskell']
