#----------------------------------------------------------------------------------#
# 必須
#----------------------------------------------------------------------------------#
[[plugins]] # deinで必須
repo = 'Shougo/vimproc.vim'
build = 'make'

#----------------------------------------------------------------------------------#
# toml管理で便利
#----------------------------------------------------------------------------------#
[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

#----------------------------------------------------------------------------------#
# colorscheme
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'jacoborus/tender.vim'
hook_add = '''
  colorscheme tender
'''

#----------------------------------------------------------------------------------#
# statusline拡張 ale利用
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.config/nvim/royautoload/plugins/plugins-lightline.vim'

[[plugins]]
repo = 'maximbaz/lightline-ale'
depends = ['ale']

#----------------------------------------------------------------------------------#
# 非同期検証ツール
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  " 左端のカラムを常に表示
  let g:ale_sign_column_always = 1
  let g:ale_lint_on_text_changed = 0
  " ファイルを開いたときにlint実行
  let g:ale_lint_on_enter = 1
  " 保存時のみ実行する
  let g:ale_fix_on_save = 1
  let g:ale_javascript_prettier_use_local_config = 1
  let g:ale_javascript_prettier_eslint_options = '--single-quote --trailing-comma es5 --no-semi'
  nmap <Leader>aj <Plug>(ale_previous_wrap)
  nmap <Leader>ak <Plug>(ale_next_wrap)
  let g:ale_fixers = {
    \ 'javascript': ['prettier-eslint', 'prettier_standard'],
    \ 'jsx': ['prettier-eslint', 'prettier_standard'],
    \ 'vue': ['prettier-eslint', 'prettier_standard'],
    \ }
'''

#----------------------------------------------------------------------------------#
# インデント補助
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
  let g:indent_guides_start_level = 2
'''

#----------------------------------------------------------------------------------#
# ファイルブラウザ補助
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = 'source ~/.config/nvim/royautoload/plugins/plugins-denite.vim'
depends = ['denite-gtags']

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'noremap <Leader>n :NERDTreeToggle<CR>'

#----------------------------------------------------------------------------------#
# 高速検索ツール
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'nixprime/cpsm'
build = 'sh -c "env PY3=ON ./install.sh"'

#----------------------------------------------------------------------------------#
# gitツール
#----------------------------------------------------------------------------------#
[[plugins]]
repo = "tpope/vim-fugitive"
hook_add = 'source ~/.config/nvim/royautoload/plugins/plugins-vim-fugitive.vim'

#----------------------------------------------------------------------------------#
# カッコ補完
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'cohama/lexima.vim'

#----------------------------------------------------------------------------------#
# 移動補完
#----------------------------------------------------------------------------------#
[[plugins]] # vimの移動コマンド拡張
repo = 'easymotion/vim-easymotion'
hook_add = '''
  " Disable default mappings
  let g:EasyMotion_do_mapping = 0
  nmap s <Plug>(easymotion-overwin-f2)
  " Gif config
  map <Leader>l <Plug>(easymotion-lineforward)
  map <Leader>j <Plug>(easymotion-j)
  map <Leader>k <Plug>(easymotion-k)
  map <Leader>h <Plug>(easymotion-linebackward)
  " keep cursor column when JK motion
  let g:EasyMotion_startofline = 0 
  let g:EasyMotion_smartcase = 1
'''

#----------------------------------------------------------------------------------#
# タグつけ　TODO
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'lighttiger2505/gtags.vim'
hook_add = '''
  " Options
  let g:Gtags_Auto_Map = 0
  let g:Gtags_OpenQuickfixWindow = 1
'''

[[plugins]]
repo = 'jsfaint/gen_tags.vim'
hook_add = '''
  let g:gen_tags#ctags_auto_gen = 1
  let g:gen_tags#gtags_auto_gen = 1
'''

[[plugins]]
repo = 'ozelentok/denite-gtags'

#----------------------------------------------------------------------------------#
# terminal拡張　TODO
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'Shougo/deol.nvim'

#----------------------------------------------------------------------------------#
# チートシート　TODO
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'reireias/vim-cheatsheet'
hook_add = 'let g:cheatsheet#cheat_file = "~/.config/nvim/cheatsheet.md"'

#----------------------------------------------------------------------------------#
# 置き換え強化
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'tpope/vim-abolish'
# crs "SnakeCase" → "snake_case"
# crm "mixed_case" → "MixedCase"
# crc "camel_case" → "camelCase"
# cru "upper_case" → "UPPER_CASE"
