[[plugins]]
repo = 'Shougo/deol.nvim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'ozelentok/denite-gtags'

[[plugins]]
repo = 'slim-template/vim-slim'
hook_add = '''
  autocmd BufRead,BufNewFile *.slim setfiletype slim
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
  let g:indent_guides_start_level = 2
'''

[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
  nmap <Leader>/ <Plug>(caw:hatpos:toggle)
  vmap <Leader>/ <Plug>(caw:hatpos:toggle)
  nmap <Leader>0 <Plug>(caw:zeropos:toggle)
  vmap <Leader>0 <Plug>(caw:zeropos:toggle)
'''
# 行の最初の文字の前にコメント文字をトグル
# 行頭にコメントをトグル

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let g:ale_sign_column_always = 1
  let g:ale_lint_on_text_changed = 0
  let g:ale_lint_on_enter = 1
  nmap <Leader>k <Plug>(ale_previous_wrap)
  nmap <Leader>j <Plug>(ale_next_wrap)
'''
# 左端のカラムを常に表示
# 保存時のみ実行する
# ファイルを開いたときにlint実行
# Space + kで次の指摘へ、Space + jで前の指摘へ移動

[[plugins]]
repo = 'reireias/vim-cheatsheet'
hook_add = 'let g:cheatsheet#cheat_file = "~/.config/nvim/cheatsheet.md"'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'nmap <Leader>n :NERDTreeToggle<CR>'

[[plugins]]
repo = 'nixprime/cpsm'
build = 'env PY3=ON ./install.sh'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['denite-gtags']
hook_add = 'source ~/.config/nvim/royautoload/plugins/plugins-denite.vim'

[[plugins]]
repo = "tpope/vim-fugitive"
hook_add = 'source ~/.config/nvim/royautoload/plugins/plugins-vim-fugitive.vim'
