#----------------------------------------------------------------#
# Syntax Highlight
#----------------------------------------------------------------#
[[plugins]] # css in js
repo = 'styled-components/vim-styled-components'
# https://github.com/styled-components/vim-styled-components/pull/80
# このmainにマージするやる気がないらしい...
rev = 'develop'
on_ft = ['typescript', 'typescriptreact', 'javascript', 'javascriptreact']

[[plugins]] # haskell
repo = 'neovimhaskell/haskell-vim'
on_ft = ['haskell']

#----------------------------------------------------------------#
# Config for each Lang
#----------------------------------------------------------------#

[[plugins]]
repo = 'prettier/vim-prettier'
build = 'yarn install'
on_ft = ['typescript', 'typescriptreact', 'javascript', 'javascriptreact', 'css', 'less', 'scss', 'json', 'graphql', 'markdown', 'vue', 'yaml', 'html']
hook_source = '''
  let g:prettier#autoformat = 0
  autocmd BufWritePre *.js,*.jsx,*.mjs,*.ts,*.tsx,*.css,*.less,*.scss,*.json,*.graphql,*.md,*.vue,*.yaml,*.html PrettierAsync
'''

[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = ['go']

