#----------------------------------------------------------------#
# Syntax Highlight
#----------------------------------------------------------------#
[[plugins]] # javascript全般
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]] # typescript
repo = 'HerringtonDarkholme/yats.vim'
on_ft = ['typescript', 'typescript.tsx']

[[plugins]]
repo = 'ruanyl/vim-sort-imports'
on_ft = ['typescript', 'typescript.tsx', 'javascript', 'javascript.jsx']
hook_source = '''
  let g:import_sort_auto = 1
'''

[[plugins]] # graphql
repo = 'jparise/vim-graphql'
on_ft = ['typescript', 'typescript.tsx', 'javascript', 'javascript.jsx', "graphql"]
depends = ['yats.vim']

[[plugins]] # css3
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css', 'javascript.jsx', 'typescript.tsx', 'javascript', 'typescript']

[[plugins]] # styled-components
repo = 'styled-components/vim-styled-components'
on_ft = ['typescript', 'typescript.tsx', 'javascript', 'javascript.jsx']
depends = ['vim-css3-syntax']

[[plugins]] # sass
repo = 'cakebaker/scss-syntax.vim'
on_ft = ['scss']
depends = ['vim-css3-syntax']

[[plugins]] # node
repo = 'moll/vim-node'
on_ft = ['javascript']

[[plugins]] # toml
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]] # json
repo = 'elzr/vim-json'
on_ft = ['json']

[[plugins]] # elm
repo = 'andys8/vim-elm-syntax'
on_ft = ['elm']

[[plugins]] # markdown
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']
hook_source = '''
  autocmd BufNewFile,BufReadPost *.md set filetype=markdown
  let g:vim_markdown_folding_disabled = 1
'''

[[plugins]] # markdown
repo = 'previm/previm'
on_ft = ['markdown']
hook_source = '''
  let g:previm_open_cmd = 'open -a Google\ Chrome'
  let g:previm_enable_realtime = 1
'''

[[plugins]] # haskell
repo = 'neovimhaskell/haskell-vim'
on_ft = ['haskell']

[[plugins]] # ruby
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]] # ruby-formatter
repo = 'ruby-formatter/rufo-vim'
on_ft = ['ruby']
hook_source = '''
  let g:rufo_auto_formatting = 1
'''

[[plugins]] # html
repo = 'othree/html5.vim''
on_ft = ['html']

[[plugins]] # ionic
repo = 'akz92/vim-ionic2'
on_ft = ['html']

[[plugins]] # dockerfile
repo = 'ekalinin/Dockerfile.vim'
on_ft = ['dockerfile']

#----------------------------------------------------------------#
# Config for each Lang
#----------------------------------------------------------------#
#----------------------------------------------------------------#
# for Haskell
#----------------------------------------------------------------#
[[plugins]] # haskell indent
repo = 'nbouscal/vim-stylish-haskell'
on_ft = ['haskell']

[[plugins]] # haskell use :h hoogle
repo = 'Twinside/vim-hoogle'
on_ft = ['haskell']
