#----------------------------------------------------------------------------------#
# 高速検索ツール
#----------------------------------------------------------------------------------#
[[plugins]]
hook_source = 'source ~/.config/nvim/plugins/ddu.lua'
on_event = 'BufRead'
repo = 'Shougo/ddu.vim'

[[plugins]]
on_source = 'ddu.vim'
repo = 'Shougo/ddu-ui-ff'

[[plugins]]
on_source = 'ddu.vim'
repo = 'Shougo/ddu-source-file_rec'

[[plugins]]
on_source = 'ddu.vim'
repo = 'Shougo/ddu-kind-file'

[[plugins]]
on_source = 'ddu.vim'
repo = 'Shougo/ddu-filter-matcher_substring'

[[plugins]]
on_source = 'ddu.vim'
repo = 'shun/ddu-source-rg'

[[plugins]]
on_source = 'ddu.vim'
repo = 'shun/ddu-source-buffer'

[[plugins]]
on_source = 'ddu.vim'
repo = 'lambdalisue/mr.vim'

[[plugins]]
on_source = 'ddu.vim'
repo = 'kuuote/ddu-source-mr'

[[plugins]]
on_source = 'ddu.vim'
repo = 'Shougo/ddu-source-register'

#----------------------------------------------------------------------------------#
# 非同期検証ツール
#----------------------------------------------------------------------------------#
[[plugins]]
hook_source = 'source ~/.config/nvim/plugins/ddc.lua'
on_event = 'InsertEnter'
repo = 'Shougo/ddc.vim'

[[plugins]]
on_source = 'ddc.vim'
repo = 'Shougo/ddc-ui-pum'

[[plugins]]
on_source = 'ddc.vim'
repo = 'Shougo/ddc-ui-inline'

[[plugins]]
on_source = 'ddc.vim'
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
on_source = 'ddc.vim'
repo = 'matsui54/ddc-matcher_fuzzy'

[[plugins]]
on_source = 'ddc.vim'
repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
on_source = 'ddc.vim'
repo = 'matsui54/ddc-buffer'

[[plugins]]
on_source = 'ddc.vim'
repo = 'Shougo/ddc-converter_remove_overlap'

[[plugins]]
on_source = 'ddc.vim'
repo = 'Shougo/ddc-source-copilot'

[[plugins]]
on_source = 'ddc.vim'
repo = 'Shougo/pum.vim'

#----------------------------------------------------------------------------------#
# Github copilot
#----------------------------------------------------------------------------------#
[[plugins]]
on_source = 'ddc.vim'
hook_source = 'source ~/.config/nvim/plugins/copilot.lua'
repo = 'github/copilot.vim'


#----------------------------------------------------------------#
# Syntax Highlight
#----------------------------------------------------------------#
[[plugins]]
hook_post_update = 'TSUpdate'
hook_source = 'source ~/.config/nvim/plugins/nvim-treesitter.lua'
merged = 0
on_event = 'BufRead'
repo = 'nvim-treesitter/nvim-treesitter'

[[plugins]]
# haskell
on_ft = ['haskell']
repo = 'neovimhaskell/haskell-vim'

#----------------------------------------------------------------#
# Config for each Lang
#----------------------------------------------------------------#

[[plugins]]
on_ft = ['go']
repo = 'mattn/vim-goimports'

#----------------------------------------------------------------#
# for Haskell
#----------------------------------------------------------------#
[[plugins]]
# haskell indent
on_ft = ['haskell']
repo = 'nbouscal/vim-stylish-haskell'
