#----------------------------------------------------------------------------------#
# 高速検索ツール
#----------------------------------------------------------------------------------#
[[plugins]]
hook_source = 'source ~/.config/nvim/plugins/ddu.vim'
on_event = 'BufRead'
repo = 'Shougo/ddu.vim'

[[plugins]]
on_source = 'ddu.vim'
repo = 'Shougo/ddu-ui-ff'

[[plugins]]
on_source = 'ddu.vim'
repo = 'Shougo/ddu-source-file_rec'

[[plugins]]
on_source = 'ddu.vim'
repo = 'Shougo/ddu-kind-file'

[[plugins]]
on_source = 'ddu.vim'
repo = 'Shougo/ddu-filter-matcher_substring'

[[plugins]]
on_source = 'ddu.vim'
repo = 'shun/ddu-source-rg'

[[plugins]]
on_source = 'ddu.vim'
repo = 'shun/ddu-source-buffer'

[[plugins]]
on_source = 'ddu.vim'
repo = 'lambdalisue/mr.vim'

[[plugins]]
on_source = 'ddu.vim'
repo = 'kuuote/ddu-source-mr'

[[plugins]]
on_source = 'ddu.vim'
repo = 'Shougo/ddu-source-register'

#----------------------------------------------------------------------------------#
# 非同期検証ツール
#----------------------------------------------------------------------------------#
[[plugins]]
depends = ['denops.vim']
hook_source = 'source ~/.config/nvim/plugins/ddc.vim'
on_event = 'InsertEnter'
repo = 'Shougo/ddc.vim'

[[plugins]]
on_source = 'ddc.vim'
repo = 'Shougo/ddc-ui-native'

[[plugins]]
on_source = 'ddc.vim'
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
on_source = 'ddc.vim'
repo = 'matsui54/ddc-matcher_fuzzy'

[[plugins]]
on_source = 'ddc.vim'
repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
on_source = 'ddc.vim'
repo = 'shun/ddc-vim-lsp'

[[plugins]]
on_source = 'ddc.vim'
repo = 'matsui54/ddc-buffer'

[[plugins]]
on_source = 'ddc.vim'
repo = 'Shougo/ddc-converter_remove_overlap'

#----------------------------------------------------------------#
# Syntax Highlight
#----------------------------------------------------------------#
[[plugins]]
hook_post_update = 'TSUpdate'
hook_source = '''
lua << EOF
  require'nvim-treesitter.configs'.setup {
    ensure_installed = { "bash", "c", "c_sharp", "clojure", "cpp", "css", "dockerfile", "elixir",
      "erlang", "go", "gomod", "graphql", "haskell", "html", "http", "java", "javascript",
      "jsdoc", "json", "lua", "make", "markdown", "markdown_inline", "python", "ruby",
      "rust", "scala", "scss", "svelte", "sql", "toml", "tsx", "typescript", "vim", 
      "vue", "yaml", "zig",
    },
    highlight = {
      enable = true,
    }
  }
EOF
'''
merged = 0
on_event = 'BufRead'
repo = 'nvim-treesitter/nvim-treesitter'

[[plugins]]
# haskell
on_ft = ['haskell']
repo = 'neovimhaskell/haskell-vim'

#----------------------------------------------------------------#
# Config for each Lang
#----------------------------------------------------------------#

[[plugins]]
build = 'npm install'
hook_source = '''
  let g:prettier#autoformat = 0
  autocmd BufWritePre *.js,*.jsx,*.mjs,*.ts,*.tsx,*.css,*.less,*.scss,*.json,*.graphql,*.md,*.vue,*.yaml,*.html PrettierAsync
'''
on_ft = [
  'typescript',
  'typescriptreact',
  'javascript',
  'javascriptreact',
  'css',
  'less',
  'scss',
  'json',
  'graphql',
  'markdown',
  'vue',
  'yaml',
  'html',
]
repo = 'prettier/vim-prettier'

[[plugins]]
on_ft = ['go']
repo = 'mattn/vim-goimports'

#----------------------------------------------------------------#
# for Haskell
#----------------------------------------------------------------#
[[plugins]]
# haskell indent
on_ft = ['haskell']
repo = 'nbouscal/vim-stylish-haskell'
