#----------------------------------------------------------------#
# 構文補完
#----------------------------------------------------------------#
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
on_event = 'InsertCharPre'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  call deoplete#custom#option({
  \ 'auto_complete_delay': 200,
  \ 'smart_case': v:true,
  \ })
  call deoplete#custom#source( '_', 'min_pattern_length', 3)
'''
[[plugins]] # tabnine
repo = 'tbodt/deoplete-tabnine'
build = './install.sh'

[[plugins]] # elm
repo = 'pbogut/deoplete-elm'
on_ft = ['elm']
depends = ['deoplete.nvim']

#----------------------------------------------------------------#
# Syntax Highlight
#----------------------------------------------------------------#
[[plugins]] # javascript全般
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']

[[plugins]] # typescript
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]] # jsx
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = ['javascript', 'typescript']
depends = ['vim-javascript', 'typescript-vim']
hook_add = '''
  let g:vim_jsx_pretty_colorful_config = 1
'''
[[plugins]] # css3
repo = 'hail2u/vim-css3-syntax'
on_ft = ['javascript', 'typescript', 'css']

[[plugins]] # styled-components
repo = 'styled-components/vim-styled-components'
on_ft = ['javascript', 'typescript']
depends = ['vim-css3-syntax']

[[plugins]] # node
repo = 'moll/vim-node'
on_ft = ['javascript']

[[plugins]] # vue
repo = 'posva/vim-vue'
on_ft = ['vue']
hook_add = '''
  autocmd FileType vue syntax sync fromstart
'''

[[plugins]] # toml
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]] #nim
repo = 'zah/nim.vim'
on_ft = ['nim']

[[plugins]] # json
repo = 'elzr/vim-json'
on_ft = ['json']

[[plugins]] # elm
repo = 'ElmCast/elm-vim'
on_ft = ['elm']

[[plugins]] # markdown
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']
hook_add = '''
  autocmd BufNewFile,BufReadPost *.md set filetype=markdown
  let g:vim_markdown_folding_disabled = 1
'''

[[plugins]] # markdown
repo = 'previm/previm'
on_ft = ['markdown']
hook_add = '''
  let g:previm_open_cmd = 'open -a Google\ Chrome'
  let g:previm_enable_realtime = 1
'''

[[plugins]] # haskell
repo = 'neovimhaskell/haskell-vim'
on_ft = ['haskell']

[[plugins]] # ruby
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

#----------------------------------------------------------------#
# Config for each Lang
#----------------------------------------------------------------#
#----------------------------------------------------------------#
# for Haskell
#----------------------------------------------------------------#
[[plugins]] # haskell indent
repo = 'nbouscal/vim-stylish-haskell'
on_ft = ['haskell']

[[plugins]] # haskell use :h hoogle
repo = 'Twinside/vim-hoogle'
on_ft = ['haskell']
