[[plugins]]
# deinで必須
build = 'make'
repo = 'Shougo/vimproc.vim'

[[plugins]]
# deinのUpdateをGUIで。
# :DeinUpdate
repo = 'wsdjeg/dein-ui.vim'

#----------------------------------------------------------------------------------#
# toml管理で便利
#----------------------------------------------------------------------------------#
[[plugins]]
# カーソル位置のコンテキストに合わせてftを切り替える
on_source = 'context_filetype.vim'
repo = 'osyo-manga/vim-precious'

[[plugins]]
# カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

#----------------------------------------------------------------------------------#
# colorscheme
#----------------------------------------------------------------------------------#
[[plugins]]
hook_post_source = '''
  colorscheme kanagawa
'''
repo = 'rebelot/kanagawa.nvim'

#----------------------------------------------------------------------------------#
# statusline拡張
#----------------------------------------------------------------------------------#
[[plugins]]
hook_add = 'source ~/.config/nvim/plugins/lightline.lua'
repo = 'itchyny/lightline.vim'

#----------------------------------------------------------------------------------#
# Denops
#----------------------------------------------------------------------------------#

[[plugins]]
repo = 'vim-denops/denops.vim'

# [[plugins]]
# repo = 'neovim/nvim-lspconfig'
# hook_add = 'source ~/.config/nvim/plugins/vim-lsp.vim'
# 
[[plugins]]
hook_add = 'source ~/.config/nvim/plugins/vim-lsp.lua'
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
lua_add = '''
  vim.g.lsp_settings = {
    clangd = {
        disabled = true
    },
    ['css-languageserver'] = {
        workspace_config = {
            css = {
                validate = false
            },
            scss = {
                validate = false
            },
            less = {
                validate = false
            }
        }
    }
  }
  vim.g['lsp_settings_filetype_ruby'] = {'solargraph'}
'''
merged = 0
repo = 'mattn/vim-lsp-settings'

[[plugins]]
lua_add = '''
  vim.g.ale_disable_lsp = 1
  vim.g.ale_sign_column_always = 1
  vim.g.ale_fix_on_save = 1
  vim.g.ale_fixers = {
      ruby = {'rubocop'},
      typescript = {'eslint'},
      javascript = {'eslint'},
      svelte = {'eslint'},
      css = {'stylelint'},
      scss = {'stylelint'},
      sass = {'stylelint'},
      less = {'stylelint'}
  }
  vim.g.ale_linter_aliases = {
      svelte = {'svelte', 'typescript'}
  }
'''
repo = 'dense-analysis/ale'

#----------------------------------------------------------------------------------#
# インデント補助
#----------------------------------------------------------------------------------#
[[plugins]]
lua_add = '''
require("indent_blankline").setup {
    space_char_blankline = " ",
    show_current_context = true,
    show_current_context_start = true,
}
'''
repo = 'lukas-reineke/indent-blankline.nvim'

#----------------------------------------------------------------------------------#
# ファイルブラウザ補助
#----------------------------------------------------------------------------------#
[[plugins]]
hook_add = 'source ~/.config/nvim/plugins/fern.lua'
repo = 'lambdalisue/fern.vim'

[[plugins]]
on_source = 'fern.vim'
repo = 'lambdalisue/fern-git-status.vim'

#----------------------------------------------------------------------------------#
# gitツール
#----------------------------------------------------------------------------------#
[[plugins]]
hook_add = 'source ~/.config/nvim/plugins/vim-fugitive.lua'
repo = 'tpope/vim-fugitive'

[[plugins]]
# github
depends = ['vim-fugitive']
repo = 'tpope/vim-rhubarb'

#----------------------------------------------------------------------------------#
# コメントアウト補助
#----------------------------------------------------------------------------------#
[[plugins]]
lua_add = '''
  -- 行の最初の文字の前にコメント文字をトグル
  vim.api.nvim_set_keymap('n', '<Leader>j', '<Plug>(caw:hatpos:toggle)', {})
  vim.api.nvim_set_keymap('v', '<Leader>j', '<Plug>(caw:hatpos:toggle)', {})
  -- 行頭にコメントをトグル
  vim.api.nvim_set_keymap('n', '<Leader>J', '<Plug>(caw:zeropos:toggle)', {})
  vim.api.nvim_set_keymap('v', '<Leader>J', '<Plug>(caw:zeropos:toggle)', {})
'''
repo = 'tyru/caw.vim'

#----------------------------------------------------------------------------------#
# 移動補完
#----------------------------------------------------------------------------------#
[[plugins]]
# vimの移動コマンド拡張
lua_add = '''
  -- Disable default mappings
  vim.g.EasyMotion_do_mapping = 0
  vim.api.nvim_set_keymap('n', '<Leader>e', '<Plug>(easymotion-overwin-f2)', {noremap = true})
  vim.api.nvim_set_keymap('n', '[Easy,<k>,<t>,<n>,<s>]', '<Nop>', {})
  vim.api.nvim_set_keymap('n', '<Leader><Space>', '[Easy,<k>,<t>,<n>,<s>]', {})
  -- Gif config
  vim.api.nvim_set_keymap('', '[EasyM]s', '<Plug>(easymotion-lineforward)', {noremap = true})
  vim.api.nvim_set_keymap('', '[EasyM]t', '<Plug>(easymotion-j)', {noremap = true})
  vim.api.nvim_set_keymap('', '[EasyM]n', '<Plug>(easymotion-k)', {noremap = true})
  vim.api.nvim_set_keymap('', '[EasyM]k', '<Plug>(easymotion-linebackward)', {noremap = true})
  -- keep cursor column when JK motion
  vim.g.EasyMotion_startofline = 0 
  vim.g.EasyMotion_smartcase = 1
'''
repo = 'easymotion/vim-easymotion'

#----------------------------------------------------------------------------------#
# 置き換え強化
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'tpope/vim-abolish'
# crs "SnakeCase" → "snake_case"
# crm "mixed_case" → "MixedCase"
# crc "camel_case" → "camelCase"
# cru "upper_case" → "UPPER_CASE"

[[plugins]]
repo = 'tpope/vim-surround'
# [e] 囲いの文字
# [d] 目的の文字
# ds [e] delete surround
# cs [e] [d] change surround
# ys iw [d] you surround

#----------------------------------------------------------------------------------#
# カッコ補完
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'cohama/lexima.vim'

#----------------------------------------------------------------------------------#
# Github copilot
#----------------------------------------------------------------------------------#
[[plugins]]
hook_add = 'source ~/.config/nvim/plugins/copilot.lua'
repo = 'github/copilot.vim'
