#----------------------------------------------------------------------------------#
# colorscheme
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'rebelot/kanagawa.nvim'
lua_add = 'vim.cmd([[colorscheme kanagawa]])'

#----------------------------------------------------------------------------------#
# statusline拡張
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'nvim-tree/nvim-web-devicons'

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
depends = ['nvim-web-devicons']
lua_add = 'require("plugins.lualine").setup()'

#----------------------------------------------------------------------------------#
# LSP
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'neovim/nvim-lspconfig'
depends = ['ddc-source-lsp', 'lazydev.nvim']
lua_add = 'require("plugins.nvim-lspconfig").setup()'

[[plugins]]
repo = 'Shougo/ddc-source-lsp'

[[plugins]]
repo = 'folke/lazydev.nvim'
lua_add = 'require("lazydev").setup()'

[[plugins]]
repo = 'j-hui/fidget.nvim'
lua_add = 'require("fidget").setup({})'

#----------------------------------------------------------------------------------#
# インデント補助
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'
lua_add = 'require("ibl").setup()'

#----------------------------------------------------------------------------------#
# ファイルブラウザ補助
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'lambdalisue/fern.vim'
lua_add = 'require("plugins.fern").setup()'

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'
depends = ['fern.vim']

[[plugins]]
repo = 'lambdalisue/fern-hijack.vim'
depends = ['fern.vim', 'fern-git-status.vim']

#----------------------------------------------------------------------------------#
# gitツール
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'tpope/vim-fugitive'
lua_add = 'require("plugins.vim-fugitive").setup()'

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
lua_add = 'require("gitsigns").setup({})'

#----------------------------------------------------------------------------------#
# 移動補完
#----------------------------------------------------------------------------------#
[[plugins]]
# vimの移動コマンド拡張
repo = 'smoka7/hop.nvim'
lua_add = 'require("plugins.hop-nvim").setup()'

#----------------------------------------------------------------------------------#
# 置き換え強化
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'tpope/vim-abolish'
# crs "SnakeCase" → "snake_case"
# crm "mixed_case" → "MixedCase"
# crc "camel_case" → "camelCase"
# cru "upper_case" → "UPPER_CASE"

[[plugins]]
repo = 'github/copilot.vim'
lua_add = '''
  vim.g.copilot_no_maps = false
'''

#----------------------------------------------------------------------------------#
# コメントアウト
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'JoosepAlviste/nvim-ts-context-commentstring'
lua_add = '''
  require('ts_context_commentstring').setup({
      enable_autocmd = false,
  })
'''

[[plugins]]
repo = 'numToStr/Comment.nvim'
depends = ['nvim-ts-context-commentstring']
lua_add = '''
  require('Comment').setup({
      pre_hook = require('ts_context_commentstring.integrations.comment_nvim').create_pre_hook(),
  })
'''

