#----------------------------------------------------------------------------------#
# 高速検索ツール
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'Shougo/ddu.vim'
lua_source = 'vim.cmd([[source ~/.config/nvim/plugins/ddu.lua]])'
on_event = 'BufRead'

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'

[[plugins]]
repo = 'shun/ddu-source-rg'
on_source = 'ddu.vim'

[[plugins]]
repo = 'shun/ddu-source-buffer'
on_source = 'ddu.vim'

[[plugins]]
repo = 'lambdalisue/mr.vim'
on_source = 'ddu-source-mr'

[[plugins]]
repo = 'kuuote/ddu-source-mr'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-register'
on_source = 'ddu.vim'

#----------------------------------------------------------------------------------#
# 非同期検証ツール
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'Shougo/ddc.vim'
lua_source = 'vim.cmd([[source ~/.config/nvim/plugins/ddc.lua]])'
on_event = ['InsertEnter', 'CmdlineEnter' ]

[[plugins]]
repo = 'Shougo/ddc-ui-pum'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'

[[plugins]]
repo = 'matsui54/ddc-matcher_fuzzy'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'

[[plugins]]
repo = 'matsui54/ddc-buffer'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/pum.vim'
on_source = 'ddc-ui-pum'

[[plugins]]
repo = 'Shougo/ddc-source-cmdline'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-cmdline_history'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-around'
on_source = 'ddc.vim'

#----------------------------------------------------------------#
# Syntax Highlight
#----------------------------------------------------------------#
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_post_update = 'TSUpdate'
lua_source = 'vim.cmd([[source ~/.config/nvim/plugins/nvim-treesitter.lua]])'
merged = 0
on_event = 'BufRead'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter-context'
on_source = 'nvim-treesitter'

#----------------------------------------------------------------------------------#
# Github copilot
#----------------------------------------------------------------------------------#
[[plugins]]
repo = 'zbirenbaum/copilot.lua'
on_event = 'InsertEnter'
on_cmd = 'Copilot'
lua_source = '''
  require("copilot").setup({})
'''

# [[plugins]]
# repo = 'github/copilot.vim'
# on_event = 'InsertEnter'
# on_cmd = 'Copilot'
# lua_source = '''
#   vim.g.copilot_no_maps = false
# '''


