#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "RoyMcCrain"
email = "me@rrrr.dev"

[ui]
editor = "nvim"
default-command = "log"
pager = ["hunk", "pager"]
diff-editor = ["nvim", "-d", "$left", "$right"]
diff-formatter = ":git"

[aliases]
current = ["log", "-r", "@ | @-"]

[remotes.origin]
auto-track-bookmarks = "glob:*"

[experimental-advance-branches]
enabled-branches = ["glob:*"]
