 require'nvim-treesitter.configs'.setup {
   ensure_installed = {
           "bash",
           "c",
           "c_sharp",
           "clojure",
           "cpp",
           "css",
           "dockerfile",
           "elixir",
           "erlang",
           "go",
           "gomod",
           "graphql",
           "haskell",
           "html",
           "http",
           "java",
           "javascript",
           "jsdoc",
           "json",
           "lua",
           "make",
           "markdown",
           "markdown_inline",
           "python",
           "ruby",
           "rust",
           "scala",
           "scss",
           "svelte",
           "sql",
           "toml",
           "tsx",
           "typescript",
           "vim",
           "vue",
           "yaml",
           "zig",
   },
   highlight = {
     enable = true,
   }
 }
