vim.api.nvim_set_keymap('n', '[git]', '<Nop>', {})
vim.api.nvim_set_keymap('n', '<Leader>g', '[git]', {})
vim.api.nvim_set_keymap('n', '[git]s', ':Git<CR><C-w>T', {noremap = true})
vim.api.nvim_set_keymap('n', '[git]a', ':Gwrite<CR>', {noremap = true})
vim.api.nvim_set_keymap('n', '[git]c', ':Git commit -v<CR>', {noremap = true})
vim.api.nvim_set_keymap('n', '[git]b', ':Git blame<CR>', {noremap = true})
vim.api.nvim_set_keymap('n', '[git]d', ':Git difftool<CR>', {noremap = true})
vim.api.nvim_set_keymap('n', '[git]m', ':Gmerge<CR>', {noremap = true})
vim.api.nvim_set_keymap('n', '[git]l', ':Glog<CR>', {noremap = true})
