model_reasoning_effort = "high"

notify = [
  "powershell.exe",
  "-NoLogo","-NoProfile","-NonInteractive",
  "-ExecutionPolicy","Bypass","-WindowStyle","Hidden",
  "-File","C:\\Users\\roy\\toast.ps1"
]
model = "gpt-5-codex"

[projects."/home/roy/ghq/github.com/zero-color/agf-mall-shopify-theme"]
trust_level = "trusted"

[projects."/home/roy/ghq/github.com/zero-color/agf-cocoro-hitoiki-shopify-app"]
trust_level = "trusted"

[projects."/home/roy/ghq/github.com/zero-color/crm"]
trust_level = "trusted"

[projects."/home/roy/ghq/github.com/RoyMcCrain/dotsfile"]
trust_level = "trusted"

[mcp_servers.deepwiki]
command = "mcp-proxy"
args = ["--transport","streamablehttp","https://mcp.deepwiki.com/mcp"]
description = "Documentation for GitHub repositories"

[mcp_servers.figma]
command = "mcp-proxy"
args = ["--transport","streamablehttp","http://127.0.0.1:3845/mcp"]
description = "Figma design mode integration (local server)"

[mcp_servers.sequential-thinking]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-sequential-thinking"]
description = "Tool for step-by-step problem solving and complex reasoning"

[mcp_servers.context7]
command = "mcp-proxy"
args = ["--transport","streamablehttp","https://mcp.context7.com/mcp"]
description = "Up-to-date documentation and code examples for libraries"

[mcp_servers.tsgo]
command = "fish"
args = ["-lc", "lsmcp-tsgo"]
description = "TypeScript language server for code analysis and refactoring"

[mcp_servers.gopls]
command = "fish"
args = ["-lc", "lsmcp-gopls"]
description = "Go language server (gopls) for Go code analysis and refactoring"

[mcp_servers.chrome-devtools-mcp]
command = "npx"
args = ["-y", "chrome-devtools-mcp@latest", "--browserUrl=http://localhost:9222"]
description = "Chrome dev tool"
